/* eslint-disable */
/**
 * Generated by convex dev.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
    ApiFromModules,
    FilterApi,
    FunctionReference,
} from "convex/server";
import type * as frames from "../frames.js";

/**
 * A utility for referencing Convex functions in your app's API.
 */
declare const fullApi: ApiFromModules<{
    frames: typeof frames;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<"public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<"internal">>;
